version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps:'
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-name: '*'
        dependency-type: production
    open-pull-requests-limit: 5
